language: rust
matrix:
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      script: cargo bench
script:
  - cargo test
  - cargo test --no-default-features
